# Wine Dataset load and importing necessary libraries


In [411]:
import numpy as np
import pandas as pd
import sklearn
from sklearn import datasets

wine = datasets.load_wine()

Data Shape for Wine

In [413]:
print(wine.data.shape)

(178, 13)


Data Description of Wine Data:

In [414]:
wine

{'data': array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
         1.065e+03],
        [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
         1.050e+03],
        [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
         1.185e+03],
        ...,
        [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
         8.350e+02],
        [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
         8.400e+02],
        [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
         5.600e+02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1

X and y representing samples and labels

In [416]:
X = wine.data[:]
print(X)
y = wine.target[:]
print(y)

[[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.413e+01 4.100e+00 2.740e+00 ... 6.100e-01 1.600e+00 5.600e+02]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


Training the Data by Train_test_split

In [417]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state = 909)

In [418]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(133, 13)
(45, 13)
(133,)
(45,)


Generalization accuracy by using cross_val_score of SVM

In [447]:
#task 3 for Cross-val-score acccuracy
from sklearn.model_selection import cross_val_score
from sklearn.svm import SVC
svc = SVC()
svc.fit(X_train,y_train)
cvs1 = cross_val_score(svc, X_train, y_train)
accuracy =np.mean(cvs1)
print("Train accuracy value: ",accuracy)

#accuracy for test set
cvs2 = cross_val_score(svc, X_test, y_test)
accuracy1 = format(np.mean(cvs2))
print("Test Accuracy value: ",accuracy1)

Train accuracy value:  0.6837606837606838
Test Accuracy value:  0.6666666666666666


In [448]:
#test error and train error by svm
train_error = 1 - np.mean(cvs1)
print("Train_error is",train_error)
test_error = 1 - np.mean(cvs2)
print("Test_error is ",test_error)

svc.fit(X_train,y_train)
y_pred1 = svc.predict(X_test)
err=np.mean(y_pred1 == y_test)
print("Error Rate is :",1-err)

Train_error is 0.3162393162393162
Test_error is  0.33333333333333337
Error Rate is : 0.28888888888888886


According to Observation We can say that Accuracy value is good but can be better for training set according to the results. Moreover, for test set accuracy and error rate we can say that the values are low as expected compared to training set. We can say that according to observation, model trained is underfitting. But we can increase the both results by implementing various algorithms (Feature Enginnering, Bagging, Boosting) to increase the accuracy on both tain and test. 

Using Normalization techniques to scale data and Using pipeline for to prevent data leak into test set

In [426]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import RobustScaler
from sklearn.preprocessing import Normalizer
from sklearn.pipeline import Pipeline
from sklearn.pipeline import make_pipeline

pipe = make_pipeline(MinMaxScaler(), SVC())
pipe.fit(X_train, y_train)
pipe.score(X_test, y_test)

0.9777777777777777

Min-Max Scaler Data Normalizer using pipeline to avoid Data snooping:

In [427]:
#for min max Scaler value SVM::

from sklearn.model_selection import GridSearchCV
param_grid = {'svc__C': [0.01, 0.1, 1, 10, 100],
'svc__gamma': [0.001, 0.01, 0.1, 1, 10, 100]}
pipe = make_pipeline(MinMaxScaler(), SVC())
grid = GridSearchCV(pipe, param_grid=param_grid)
grid.fit(X_train,y_train)
print("Best cross-validation accuracy:", grid.best_score_)
score = grid.score(X_test,y_test)
print("Test set score:",score)
print("Test error Rate score:",1-score)


Best cross-validation accuracy: 0.9925925925925926
Test set score: 0.9555555555555556
Test error Rate score: 0.0444444444444444


Standard-Scaler

In [428]:
#task2 for Standard Scaler

pipe = make_pipeline(StandardScaler(), SVC())
grid = GridSearchCV(pipe, param_grid=param_grid)
grid.fit(X_train,y_train)
print("Best cross-validation accuracy:", grid.best_score_)
score = grid.score(X_test,y_test)
print("Test set score:",score)
print("Test error Rate score:",1-score)



Best cross-validation accuracy: 0.9774928774928775
Test set score: 0.9777777777777777
Test error Rate score: 0.022222222222222254


Robust-Scaler

In [430]:
#task for Robust Scaler
pipe = make_pipeline(RobustScaler(), SVC())
grid = GridSearchCV(pipe, param_grid=param_grid)
grid.fit(X_train, y_train);
print("Best cross-validation accuracy:", grid.best_score_)
score= grid.score(X_test,y_test)
print("Test set score:",score)
print("Test error Rate score:",1-score)


Best cross-validation accuracy: 0.9925925925925926
Test set score: 0.9777777777777777
Test error Rate score: 0.022222222222222254


In [431]:
#task for Normalizer
pipe = make_pipeline(Normalizer(), SVC())
grid = GridSearchCV(pipe, param_grid=param_grid)
grid.fit(X_train, y_train);
print("Best cross-validation accuracy:", grid.best_score_)
score = grid.score(X_test,y_test)
print("Test set score:",score)
print("Test error Rate score:",1-score)


Best cross-validation accuracy: 0.9321937321937324
Test set score: 0.9555555555555556
Test error Rate score: 0.0444444444444444


According to Observation we observe that Robust-Scaler and Standard-Scaler gives the same Accuracy for both is same. We use RobustScaler in this case and we predict the labels using this method as considering the best fit and normalizer according to the answers. 

In [435]:
#prediction by robust as most best 

pipe = make_pipeline(RobustScaler(), SVC())
grid = GridSearchCV(pipe, param_grid=param_grid)
grid.fit(X_train, y_train);
score= grid.score(X_test,y_test)
y_pred = grid.predict(X_test)
err = np.mean(y_pred == y_test)
print("Labels are as Follows:",y_pred)
print("Error Rate is :",1-err)
print("Target_names",wine['target_names'])

Labels are as Follows: [1 2 0 1 0 0 1 2 1 0 1 0 0 2 1 1 1 0 2 2 2 1 1 1 1 1 0 0 1 2 2 2 2 0 1 0 1
 1 1 1 0 1 0 1 1]
Error Rate is : 0.022222222222222254
Target_names ['class_0' 'class_1' 'class_2']


In [513]:
#task 8 for MLP Classifier
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split, cross_val_score
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify= y,random_state=909)
mlp = MLPClassifier(solver='lbfgs', activation='tanh', random_state=0, hidden_layer_sizes=[10]).fit(X_train,y_train)
train_accuracy = cross_val_score(mlp, X_train, y_train)
print("Accuracy of Training Set: ",np.mean(train_accuracy))

test_accuracy = cross_val_score(mlp, X_test, y_test)
print("Accuracy of Test Set: ",np.mean(test_accuracy))
Err = (1 - np.mean(test_accuracy))
print("Test Error Rate: ",Err)
print("Score through mlp classifier is:",mlp.score(X_test, y_test))
 

Accuracy of Training Set:  0.8266666666666668
Accuracy of Test Set:  0.76
Test Error Rate:  0.24
Score through mlp classifier is: 0.72


In [510]:
test_error = 1 - np.mean(test_accuracy)
print("Test_error is ",test_error)

mlp.fit(X_train,y_train)
y_pred1 = mlp.predict(X_test)
err=np.mean(y_pred1 == y_test)
print("Error Rate is using MLP:",1-err)


Test_error is  0.16000000000000014
Error Rate is using MLP: 0.31999999999999995


We can see that after  implementing MLPClassifier and cross_val score we get less error rate for cross val score compared to MLP Classifier. 

# USPS Dataset

loading the data and concatenating them 

In [436]:
file1 = np.genfromtxt("zip.train", delimiter=" ")
print(file1.shape)
file2 = np.genfromtxt("zip.test", delimiter=" ")
print(file2.shape)

(7291, 257)
(2007, 257)


In [437]:
dataset2 = np.concatenate([file1,file2])
dataset2.shape
X2 = dataset2[:,1:]
y2 = dataset2[:,0]

Splitting the Data into Train test

In [400]:
from sklearn.model_selection import train_test_split
X_train2,X_test2,y_train2,y_test2 = train_test_split(X2,y2,random_state=909)

Using svm and cross_val to predict the accuracy

In [438]:
from sklearn.model_selection import cross_val_score
from sklearn.svm import SVC
svc = SVC()
svc.fit(X_train2,y_train2)
cvs1 = cross_val_score(svc, X_train2, y_train2)
accuracy = np.mean(cvs1)
print("For Train accuracy value: ",accuracy)

cvs2 = cross_val_score(svc, X_test2, y_test2)
accuracy1 = format(np.mean(cvs2))
print("For Test accuracy value: ",accuracy1)

For Train accuracy value:  0.9691661652859412
For Test accuracy value:  0.9561290322580644


In [404]:
#test error and train error by svm
train_error = 1 - np.mean(cvs1)
print("Train_error",train_error)
test_error = 1 - np.mean(cvs2)
print("Test_error",test_error)

Train_error 0.03083383471405876
Test_error 0.04387096774193555


For all normalization using all scaler and getting their accuracy and error values

In [405]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import RobustScaler
from sklearn.preprocessing import Normalizer
from sklearn.pipeline import Pipeline
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import Normalizer

pipe = make_pipeline(MinMaxScaler(), SVC())
pipe.fit(X_train2, y_train2)
pipe.score(X_test2, y_test2)

0.9767741935483871

In [407]:
from sklearn.model_selection import GridSearchCV
param_grid = {'svc__C': [0.01, 0.1, 1, 10, 100],
'svc__gamma': [0.001, 0.01, 0.1, 1, 10, 100]}
pipe = make_pipeline(MinMaxScaler(), SVC())
grid = GridSearchCV(pipe, param_grid=param_grid)
grid.fit(X_train2,y_train2)
print("Best cross-validation accuracy:", grid.best_score_)
score = grid.score(X_test2,y_test2)
print("Test set score:",score)
print("Test error Rate score:",1-score)


Best cross-validation accuracy: 0.9704565907139149
Test set score: 0.9793548387096774
Test error Rate score: 0.020645161290322567


In [408]:
pipe = make_pipeline(StandardScaler(), SVC())
grid = GridSearchCV(pipe, param_grid=param_grid)
grid.fit(X_train2,y_train2)
print("Best cross-validation accuracy:", grid.best_score_)
score = grid.score(X_test2,y_test2)
print("Test set score:",score)
print("Test error Rate score:",1-score)


Best cross-validation accuracy: 0.9651499771164694
Test set score: 0.9750537634408603
Test error Rate score: 0.024946236559139745


In [409]:
pipe = make_pipeline(RobustScaler(), SVC())
grid = GridSearchCV(pipe, param_grid=param_grid)
grid.fit(X_train2, y_train2);
print("Best cross-validation accuracy:", grid.best_score_)
score= grid.score(X_test2,y_test2)
print("Test set score:",score)
print("Test error Rate score:",1-score)
print("Best parameters:", grid.best_params_)

Best cross-validation accuracy: 0.8937365977075331
Test set score: 0.923010752688172
Test error Rate score: 0.07698924731182799
Best parameters: {'svc__C': 100, 'svc__gamma': 0.001}


In [410]:
pipe = make_pipeline(Normalizer(), SVC())
grid = GridSearchCV(pipe, param_grid=param_grid)
grid.fit(X_train2, y_train2);
print("Best cross-validation accuracy:", grid.best_score_)
score = grid.score(X_test2,y_test2)
print("Test set score:",score)
print("Test error Rate score:",1-score)

Best cross-validation accuracy: 0.9717469132945599
Test set score: 0.9789247311827957
Test error Rate score: 0.02107526881720434


In [441]:
pipe = make_pipeline(MinMaxScaler(), SVC())
grid = GridSearchCV(pipe, param_grid=param_grid)
grid.fit(X_train2,y_train2)

score = grid.score(X_test2,y_test2)
y_pred = grid.predict(X_test2)
err = np.mean(y_pred == y_test2)
print("Labels are as Follows:",y_pred)
print("Test Error Rate is :",1-err)


Labels are as Follows: [7. 0. 5. ... 6. 9. 6.]
Test Error Rate is : 0.020645161290322567


The result for minmax scaler were best as the error rate is only 0.02 and and it has very good prediction accuracy.

In [507]:
#task 8 
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split, cross_val_score
X_train2, X_test2, y_train2, y_test2 = train_test_split(X2, y2,random_state=909)
mlp = MLPClassifier(solver='adam', activation='tanh', random_state=909, hidden_layer_sizes=[10]).fit(X_train2,y_train2)
train_accuracy1 = cross_val_score(mlp, X_train2, y_train2)
print("Accuracy of Training Set: ",np.mean(train_accuracy1))

test_accuracy1 = cross_val_score(mlp, X_test2, y_test2)
print("Accuracy of Test Set: ",np.mean(test_accuracy))
Err = (1 - np.mean(test_accuracy1))
print("Test Error Rate: ",Err)
print("Score through mlp classifier is:",mlp.score(X_test2, y_test2))

D:\Anaconda\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
D:\Anaconda\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
D:\Anaconda\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
D:\Anaconda\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
D:\Anaconda\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer

Accuracy of Training Set:  0.9317358057831052


D:\Anaconda\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
D:\Anaconda\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
D:\Anaconda\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
D:\Anaconda\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


Accuracy of Test Set:  0.76
Test Error Rate:  0.07741935483870976
Score through mlp classifier is: 0.9453763440860216


D:\Anaconda\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [514]:
test_error2 = 1 - np.mean(test_accuracy1)
print("Test_error is ",test_error2)

mlp.fit(X_train2,y_train2)
y_pred2 = mlp.predict(X_test2)
err=np.mean(y_pred2 == y_test2)
print("Error Rate is using MLP:",1-err)


Test_error is  0.07741935483870976
Error Rate is using MLP: 0.06494623655913978


D:\Anaconda\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:471: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)


In this las task we get good accuracy value through mlp classifier than the cross value score.We used lbgfs cause both datasets are large we can also use adam but it was giving errors.